name: diff

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      # Checks-out this repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      # Checks-out the repositories to be diffed
      - name: checkout repos
        run: scripts/clone.sh
      - name: list repos
        run: ls -l repos/
      - name: diff repos
        run: scripts/diff-repos.sh
