name: diff

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'acend/hugo-training-template'
          ref: 'main'
          path: 'hugo-training-template'
      - name: list files
        run: ls -la hugo-training-template/
      - name: cache repo
        uses: actions/cache@v2
        with:
          path: hugo-training-template/
          key: hugo-training-template-repo

  checkout-amm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'puzzle/amm-techlab'
          ref: 'master'
          path: 'amm-techlab'
      - name: list files
        run: ls -la amm-techlab/
      - name: cache repo
        uses: actions/cache@v2
        with:
          path: amm-techlab/
          key: amm-techlab-repo

  diff:
    runs-on: ubuntu-latest
    needs: [checkout-template, checkout-amm]
    steps:
      - name: get template cache
        uses: actions/cache@v2
        with:
          path: hugo-training-template/
          key: hugo-training-template-repo
      - name: get amm cache
        uses: actions/cache@v2
        with:
          path: amm-techlab/
          key: amm-techlab-repo
      - name: diff package.json
        run: diff hugo-training-template/package.json amm-techlab/package.json
